version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: essentia_php
        volumes:
            - .:/var/www
        restart: unless-stopped
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: essentia_mysql
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: essentia_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
